### ISSUE TITLE
Request for a how-to guide: keeping your app up to date

### ISSUE THREAD

**Issue by oren** [developit/preact-cli#102]
How do I make sure my application has the recent changes of Preact CLI? I assume I can run the create command and create a new app and copy all the files in the components and routes folder and whatever else I added but that sounds error prone and slow.

**Comment by thangngoc89** [comment]
@oren If preact-cli follow the semver correctly, you just need to bump preact-cli version if there is a minor/patch release. If it's a major release (which introduces breaking changes), there should be a guide to tell user how to update.

**Comment by oren** [comment]
Do i need to make any changes in package.json?
What is the exact command I should run in the terminal? Npm update?
Also, what about files like app.js, package.json, or the manifest file. What if they should also change? Is that considered a major change?

Thanks!

**Comment by thangngoc89** [comment]
@oren `npm update` should do the trick. 

preact-cli doesn't care about `app.js` `package.json`, or the manifest file. The only requirements is an `index.js` at cwd that exports a component. (see the `empty` example). Everything else is optional and have it fallback.

**Comment by oren** [comment]
Got it. 

One more question: 
`npm update` will only update the dependencies. When do I know it's time for updating the cli itself (`sudo npm update -g preact-cli`) and generating a new app?

**Comment by thangngoc89** [comment]
`npm -g update`

**Comment by lukeed** [comment]
The CLI really is just a config generator. The templates/boilerplates that are included are mostly a starting point. Across all libraries, it's generally assumed that the user will have progressed their app code far enough along that the dummy-templates won't matter anymore.

The important part is maintaining config & build functionality. That's what _will_ be updated & synced in the future.

**Comment by oren** [comment]
@thangngoc89 I believe you answered the question '**how** to upgrade the preact-cli'. I was asking '**when** should I do it'.

@lukeed got it. The reason I am asking is let's say the cli will have in the future a new feature that require a new dependency in package.json. If I don't re-generate a preact app I'll never have it. In those situation I feel like it's important be notified that I should re-generate my app and maybe copy paste some files to the new generated folder. At least that's how I see things. Please correct me if I am wrong.

**Comment by lukeed** [comment]
I guess it depends what we're calling a "feature" ... or what that feature is. 

As an example, let's assume a new feature is added which modifies or adds a new service worker behavior. All you have to do is update your global and/or local `preact-cli` version, and all your applications (tied to the CLI) will inherit the new feature automatically. This is because it's config/build code that's included with the CLI source.

Similarly, the same sort of game plan applies to #56 when it lands. Everyone who already uses `preact-cli` will **not** have to scrap their existing projects and build from a new empty template. Instead, we'll all just bump our dependency version --- just like any other library or module dependency. Does that make sense?

I feel comfortable saying that 99.9% of the time, there won't be a template update. If there is, it'd be minor things (like #82). No one is installing and using `preact-cli` for its templates. Instead, we're all here for the automatic build-stuff that makes life easier.

**Comment by oren** [comment]
got it. should this be part of an FAQ page? Should we close this issue? I am just worried that a lot of the discussions on github are being lost if it's not move to a more visible/official place.

**Comment by developit** [comment]
Definitely part of a FAQ yup, I think a lot of people don't realize this is something we want to keep as sealed up as possible within the confines of the CLI - you really should never have to update your application code in order to move forward with the CLI, because it's a generic "preact app bundler".  

We could use this issue to track the bit you mentioned about the global `preact-cli` install - for that I'd actually like to have the CLI check for new versions periodically and notify you of an update (a bunch of the other ones do this).

**Comment by kahlil** [comment]
@developit this is a great update notifier: https://www.npmjs.com/package/update-notifier

**Comment by reznord** [comment]
@kahlil update-notifier will be available in the next version of preact-cli.

Keeping an app up-to-date in preact-cli will not be a problem since we are adding preact-cli as a dependency, it will always have the latest changes. So, just bumping up the `preact-cli` version will do the work.

**Comment by kahlil** [comment]
nice
