### ISSUE TITLE
Request for a reference document: list of polyfills and supported browsers

### ISSUE THREAD

**Issue by oren** [developit/preact-cli#113]
It would be valuable to add an official reference doc that lists all polyfills that comes with preact-cli and what browser version each one supports.

**Comment by thangngoc89** [comment]
Preact-cli ships with promise and fetch polyfill ( in fact, it's unfetch, the minimal version, not full specs). 
I'm not sure what do you mean by support browser? Polyfill is for browsers that dont have the feature. You can view the list of browser that supports a feature on camiuse.com

**Comment by oren** [comment]
Thanks!

What about `Object.assign`? I heard it's not needed if you use babel transform plugin. 
I looked at the code base and found [this line](https://github.com/developit/preact-cli/blob/master/src/lib/babel-config.js#L21) so I assume it means I don't need to add it myself since it comes with preact-cli?

I think that having a list like this as part of the documentation:
```
window.Promise - not working on : IE 11, android 4.4
window.Fetch - not working on: IE 11, safari 10.2, android 4.4.4
Object.assign - not working on: any IE, Chrome 44
```

How else do people new to the project learn about the available polyfills?

**Comment by thangngoc89** [comment]
You don't need to worry about this stuff. If you use shiny new features (aka ES2015) then you'll have to worry about it. Otherwise, just develop your website. If you are not sure, use [Polyfill CDN](https://polyfill.io/v2/docs/) . It will take care of everything. 

My advice is: analyze your user base, only polyfill what's needed. For example: You can use plain old XMLHttpRequest instead of fetch.
