### ISSUE TITLE
Extend PostCSS to use plugins other than autoprefixer

### ISSUE THREAD

**Issue by OngeUK** [developit/preact-cli#166]
Having PostCSS autoprefixer is a really useful feature, but as far [as I can tell](https://github.com/developit/preact-cli/blob/5f268a8d444d6449372343f75ce6aab4e616c997/src/lib/webpack/webpack-base-config.js#L194), autoprefixer is the only PostCSS plugin that can be used.

Would it be possible to extend the PostCSS functionality to enable the use of other plugins, preferably via a `postcss.config.js` file?

**Comment by ethanroday** [comment]
@OngeUK, as of `1.3.0`, you can use `preact.config.js` to customize the Webpack config of your project. Using this, you could configure the PostCSS functionality in a number of ways. You could, for example, modify the `postcss` entry in the default `webpack.LoaderOptionsPlugin` to override the list of PostCSS plugins. For example, in your `preact.config.js` (WARNING: UNTESTED):

```JS
export default function (config, env, helpers) {
  let loaderOptionsPlugins = helpers.getPluginsByName(config, 'LoaderOptionsPlugin');
  for (let i = 0; i < loaderOptionsPlugins.length; i++) {
    let loaderOptionsPlugin = loaderOptionsPlugins[i];
    if (loaderOptionsPlugin.options.postcss) {
      loaderOptionsPlugin.options.postcss = () => [
        //Set your list of postcss plugins here (make sure to add them to your dev dependencies)
      ]
    }
  }
}
```

Alternatively, instead of replacing the `postcss` entry, you could _remove_ it entirely, then add a `postcss.config.js` in your project directory. With no specifically configured loader options, `postcss-loader` will automatically look for your config file.

**Comment by sylvainpolletvillard** [comment]
@ethanroday Thanks for the code. However, since Preact CLI already use PostCSS with Autoprefixer, I think it would be a great addition to have built-in support for `postcss.config.js` file

**Comment by sylvainpolletvillard** [comment]
Removing options.postcss from the default config let me use postcss.config.js files :+1: 
```
export default function (config, env, helpers) {
	const options = helpers.getPluginsByName(config, 'LoaderOptionsPlugin')
		.find(({ plugin }) => plugin.options.options.postcss)
		.plugin.options.options;

	delete options.postcss; // will use postcss.config.js
}
```

**Comment by OngeUK** [comment]
Thanks for the feedback - the suggested `preact.config.js` approach works well.

**Comment by louisremi** [comment]
It seems this approach no longer works with preact-cli v2.0.0. :-/

**Comment by louisremi** [comment]
And here's the new workaround for preact-cli v2.0.0:
```
export default function (config, env, helpers) {
    const postcssLoader = helpers.getLoadersByName(config, 'postcss-loader');
    postcssLoader.forEach(({ loader }) => ( delete loader.options ));
}
```
:-)
