### ISSUE TITLE
Upgrading preact from 1.1.1 to 1.3.0 required uninstalling preact-cli

### ISSUE THREAD

**Issue by oren** [developit/preact-cli#197]
In order to upgrate preact cli I had to do the following:
```
sudo npm uninstall -g preact-cli
sudo npm install -g preact-cli
```
(sudo npm update -g preact-cli kept the old version from some reason)

I would like to understand if that's normal, or maybe it's something specific to my laptop.
Here are more details about my setup:
```
cat /etc/lsb-release 
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

node --version
v7.10.0

npm --version
4.2.0
```

**Comment by reznord** [comment]
For me, it works perfectly fine. I have installed `1.1.1` and then upgraded it to `1.3.0` just by running  `npm install -g preact-cli`

This may be because you are running it as sudo? 

Btw, installing `npm` with `sudo` is not recommended. You can check the following guides for moving away from `sudo`

- https://docs.npmjs.com/getting-started/fixing-npm-permissions
- https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

Hope this helps !!

**Comment by oren** [comment]
very helpful links. thank you!

**Comment by reznord** [comment]
Did your issue got resolved?

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by oren** [comment]
Not sure since I already have the recent version. I will close this untill the next version upgrade. Thank you.
