### ISSUE TITLE
Misleading docs with unpublished package

### ISSUE THREAD

**Issue by ooade** [developit/preact-cli#229]
I feel the docs shouldn't be updated on the master branch till the package is released because it's kinda misleading. I tried the --prerenderUrls option for couple minutes only to find out it wasn't published to npm yet.

**Comment by yavorski** [comment]
@ooade 
Hint: Read the `tagged` docs if you want to reed the docs for the exact version you are using.
Example with `1.3.0`: https://github.com/developit/preact-cli/tree/1.3.0

**Comment by lukeed** [comment]
Oh, yeah. Looks like we got side-tracked on actually getting a release out! Had a lot of PRs flying in this week. 😅

**Comment by ooade** [comment]
@yavorski IKR. But I guess my issue is pointless since everyone using preact-cli know how to use github well 😥

**Comment by yavorski** [comment]
@ooade 
In general that's one the benefits using `tags`. You could search for more. I'm sure you will like it!

**Comment by krokofant** [comment]
@ooade If they don't know how to use github then why would they look at the master docs instead of the npm-published docs? 🤔

**Comment by developit** [comment]
Ideally I'd like to have the docs for whatever the current release is hosted elsewhere, perhaps on the Preact website.  That seems like a nicer and more official solution to @ooade's concern - I've actually had a few questions about the docs being master VS release recently.  It's usually because I'm holding up a release, which I think we can also solve by me not being the gatekeeper for releases haha.

**Comment by ooade** [comment]
That's better @developit :)
