### ISSUE TITLE
Use "nyr" for handling scripts

### ISSUE THREAD

**Issue by reznord** [developit/preact-cli#251]
Taking suggestion from the [comment](https://github.com/developit/preact-cli/pull/246#issuecomment-317205155) by @developit, it is better to go with [nyr](https://github.com/simonkberg/nyr) for scripts.

**Comment by yavorski** [comment]
Replace `scripts` section in `package.json` with yarn specifics if user is installing with `--yarn`? 
Or directly provide different `package.json` file?

**Comment by reznord** [comment]
> Replace scripts section in package.json with yarn specifics if user is installing with

That is what happening currently. You can see the code [here](https://github.com/developit/preact-cli/blob/master/src/lib/setup.js#L42-L64).

**Comment by yavorski** [comment]
@reznord I see. Can you please elaborate a bit more on the actual issue?

**Comment by reznord** [comment]
( slacking you )

**Comment by developit** [comment]
The issue was that you might install via yarn but then run via npm, or you uninstall yarn or something. I actually asked about this on Twitter and it seems like people just use `npm` in npm scripts, even if they only intend to run via Yarn.  The reason is because `npm` is always installed if you have node (which is required for running preact-cli and yarn), but `yarn` is an optional thing, not installed by either - so `npm` is always available, `yarn` not necessarily so.

**Comment by yavorski** [comment]
So if `npm` and `npm run` is always available, why we should use `yarn run` or `nyr sth` at all?

**Comment by developit** [comment]
That was sortof my feeling, but I know people are passionate about Yarn 🤣

**Comment by lukeed** [comment]
IMO not really needed 😄

**Comment by yavorski** [comment]
I truly believe we don't need to complicate current setup in this way. :)

**Comment by thangngoc89** [comment]
I always use npm in package.json scripts. Even though I always use yarn
