### ISSUE TITLE
2x app instances when doing a production build

### ISSUE THREAD

**Issue by nephix** [developit/preact-cli#391]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I run `preact build --template src/template.html` and start my web app, the "app" div is initialized twice:
![App initialized twice](http://666kb.com/i/dncawwypcwyzk41ds.png)
When I run `preact watch` it's only initialized once.

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm not sure what is causing this, so I can't provide any steps. Here's my `src/index.js` and `src/components/app.js`:
https://gist.github.com/nephix/f62d11c63d73c4453201ab28d39d2bac

**What is the expected behavior?**
That the `<div id="app">` is only rendered once when I run `preact build`. Has anyone experienced the same issue and knows a workaround/fix?

**Please mention other relevant information.**
- preact-cli 1.4.1
- node version 6.11.1
- npm version 5.4.2
- Operating system macosx

**Comment by nephix** [comment]
I was able to solve the issue. It was caused by a noscript tag that we integrated because Google Tag Manager told us to. Once we removed it, the app was only initialized once.
Here's the complete template that we used (GTM IDs removed):
https://gist.github.com/nephix/10e76257f20fd18bcab448bad00e5a59

I'll leave this open just in case it needs to be referenced for a solution. For us it's ok to remove the noscript tag, so it's solved on our side.

**Comment by lukeed** [comment]
Unfortunately, this is caused because the `noscript` tag is the first `document.body` child. Preact CLI [renders directly into the first `body` node](https://github.com/developit/preact-cli/blob/master/src/lib/entry.js#L17-L22). 

So, if your pre-rendered page is:

```html
<body>
  <noscript />
  <div#app />
</body>
```

...then the CLI is looking at `noscript`, deciding that the app isn't mounted, then re-mounting it.

For your case, I'd move the GTM to the head.
