### ISSUE TITLE
Error: Exited with status 69

### ISSUE THREAD

**Issue by Ketcap** [developit/preact-cli#419]
After updating preact-cli got error while creating project. Project folder is created by the way.

![screen shot 2017-10-22 at 2 04 05 pm](https://user-images.githubusercontent.com/7689820/31861213-e6321f3c-b731-11e7-8ed3-dc11662131c4.png)

- node version : 8.1.4
- npm version : 5.5.1
- Operating system : macOS Sierra 10.12.6
- preact cli : 2.0.2

**Comment by reznord** [comment]
Actually you are doing it wrong. The command for creating a new project using cli is `preact create default my-app --yarn`.

You should pass flags to the end. 

In the above command, `default` is aliased to `preactjs-templates/default` a git repo & `my-app` is the name of the folder in which you want to create the project.

If you don't provide `my-app`, it will prompt the user since that is a required value.
