### ISSUE TITLE
Write `template.html` to Project

### ISSUE THREAD

**Issue by lukeed** [developit/preact-cli#428]
**Do you want to request a *feature* or report a *bug*?**

Feature

**If this is a feature request, what is motivation or use case for changing the behavior?**

In order to make any customizations to the `lib/template.html`, one has to manually copy & paste the contents into the current directory.

I have two suggestions, an either/or scenario:

1) Write the `lib/template.html` to the project by default during `create`
2) Add some kind of command or flag to print the current template to project.
    _This could go nicely with #427 + its duplicate requests... write all internal configs to repo?_

**Comment by reznord** [comment]
This is totally a much needed thing for the next release. I spoke to @developit on this and he said he will look into it when he gets some time.

**Comment by prateekbh** [comment]
>1. Write the lib/template.html to the project by default during create

I think this option is pretty straight forward and super easy to understand and we should do this by default. Thoughts?

FYI I have free cycles now. feel free to assign me stuff

**Comment by developit** [comment]
I have some time too that I can commit to this. Reason I've held off pushing for this is because I really want the `template.html` to be simpler than it currently is, and not specific to `html-webpack-plugin` (since that would be a very leaky abstraction).  Ideally, we should look for an `index.html` in the user's project since that's the built name anyway (nice to keep things 1:1).  That file would just be a simple HTML document, and preact-cli would manage parsing it into a DOM and injecting the scripts/styles/prerendered content/etc into it.

**Comment by prateekbh** [comment]
Can we split the work here and first just copy the existing one to user land, and then keep simplifying it as we go?

**Comment by prateekbh** [comment]
Closing this as #705 fixes it. Lets open a new issue for improving the template itself
