### ISSUE TITLE
[Bug] Can't use generators, build fails while uglifying

### ISSUE THREAD

**Issue by divyanshutomar** [developit/preact-cli#479]
**Do you want to request a *feature* or report a *bug*?**
Report a Bug

**What is the current behaviour?**
Not able to produce a production build.Getting the following error:

![screen shot 2018-02-03 at 1 19 34 am](https://user-images.githubusercontent.com/8142282/35752021-721ae264-0880-11e8-8fb7-e43599c2d3be.png)

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. Use a generator function in your codebase. Eg :
```
function* sagaFunc() {
  // code ....
}
```

2. Run the build command i.e. ```npm run build```

**What is the expected behaviour?**
Build process should process without errors.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version v8.5.0
- npm version 5.6.0
- Operating system macOS
- CLI version 2.1.1
- Browser Chrome

>

**Comment by developit** [comment]
I believe this can be fixed by adding your own `.babelrc` with `{ "presets": ["env"] }`

**Comment by oieduardorabelo** [comment]
hi @developit , I think this is related to [`webpack-client-config.js`](https://github.com/developit/preact-cli/blob/6742f94664cf88ca0159f809e715fd441495e653/src/lib/webpack/webpack-client-config.js#L106:L110) configuration.

currently we use webpack's internal `new webpack.optimize.UglifyJsPlugin`, which uses [UglifyJS v2](https://github.com/mishoo/UglifyJS2/tree/v2.x) and it doesn't support ES6.

in this case, we could use Babel to transform it, but we're also [ignoring transform-regenerator on preact-cli/babel](https://github.com/developit/preact-cli/blob/6742f94664cf88ca0159f809e715fd441495e653/src/lib/babel-config.js#L13:L17).

a possible solution is to use [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) instead of the internal plugin.

i could make the PR, is that a viable idea?

---

[FAILING] Test Example:

- `$ preact create default testy`
- `$ cd testy`
- open `src/index.js` and add:

```
import './style';
import App from './components/app';

export default App;

function* gen() {
  yield "world"
}

let it = gen();
console.log(it.next())
```
- it works when I open `http://localhost:8080/`
- and running `npm run build`:
<img width="765" alt="screen shot 2018-09-12 at 7 07 00 pm" src="https://user-images.githubusercontent.com/829902/45407966-127d2400-b6bf-11e8-8459-342788e400b9.png">

[SUCCESS] Test Example:

- from the example above, add `npm install uglifyjs-webpack-plugin`
- edit `node_modules/preact-cli/lib/lib/webpack/webpack-client-config.js`
- replace current Uglify by the plugin installed
- and running `npm run build`:
<img width="987" alt="screen shot 2018-09-12 at 7 10 16 pm" src="https://user-images.githubusercontent.com/829902/45408124-8f100280-b6bf-11e8-8409-3f7a1563f61d.png">

**Comment by prateekbh** [comment]
Can u try the same with preact-cli@next
.9
