### ISSUE TITLE
[question] flow return types?

### ISSUE THREAD

**Issue by tconroy** [developit/preact-cli#481]
Hey there. I noticed that preact supports Flow, which is awesome, however I'm having trouble finding the typings for all of Preact's methods. ie, what should the return type be fore a functional component (or the render method on a regular component, for that matter)?

reading online, it seems `Node`, `Element`, and `React$Element<any>` are common, however Preact either doesn't export these types, or in the case of the last example, is React-specific.

Any docs on this ( or even commits/PR's) would be super appreciated!

**Comment by developit** [comment]
Preact just re-exports React's flow types:
https://github.com/developit/preact/blob/master/src/preact.js.flow#L3

**Comment by smirnowld** [comment]
It doesn't seem to re-export all of them? Only `createElement`, `cloneElement`, `Component`, and `Node` are re-exported, whereas React seems to have quite a few more: https://flow.org/en/docs/react/types/

I can't seem to figure out how to use any of these type, e.g. `React.ComponentType`. Importing `{ ComponentType } from 'preact'` results in _Cannot import ComponentType because there is no ComponentType export in preact._

**Comment by marvinhagemeister** [comment]
@smirnowld That's awesome, thanks for diving deeper into this. We'd love to get the flow typings up to par to our TypeScript definitions but lack the expertise in that area. We'd be super excited about PRs for that over at the [preact](https://github.com/developit/preact) repo.

**Comment by smirnowld** [comment]
Hold on, I'm slightly confused. Are you saying that there _is_ a problem with Preact Flowtype definitions in that they're incomplete, meaning the problem should be raised in Preact repo? If that's the case, I'm happy to take the conversation there (just having somebody acknowledge this problem is a huge boost to my sanity, which was waning...), but not sure how much I can contribute to actually solving it yet, although would definitely be happy to take a stab at it.

**Comment by marvinhagemeister** [comment]
@smirnowld There is likely a problem with our flow types. None of the members in the core team use flow and as such it doesn't get as much love as the TS types.

That said it'd be really cool if you can improve the flow definitions. You seem to have knowledge in that area. Note that if you're constraint on time, you can do a small fix every then and now. It's sometimes a bit overwhelming to try to fix every issue in one go. That can easily happen iteratively 👍
