### ISSUE TITLE
helpers.getPluginsByName(config, 'CopyWebpackPlugin') returns [] for client build

### ISSUE THREAD

**Issue by psabharwal123** [developit/preact-cli#577]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
helpers.getPluginsByName(config, 'CopyWebpackPlugin') returns [] for **client build**

**If the current behaviour is a bug, please provide the steps to reproduce.**
create preact.config.js and consle.log helpers.getPluginsByName(config, 'CopyWebpackPlugin') 

**What is the expected behaviour?**
it should not return []

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version 6.10.0
- npm version 4.1.2
- Operating system windows 10
- CLI version 2.1.0
- Browser any

**Comment by lukeed** [comment]
Hey, nice catch!

While this certainly appears like a bug, it's actually due to _how_ `copy-webpack-plugin` exports itself. While 99% of the plugins return a class, thus allowing us to match by name, this plugin returns an object instead, which makes it completely anonymous: https://github.com/webpack-contrib/copy-webpack-plugin/blob/v4.5.1/src/index.js#L169-L171

If you still need to access it, I'd recommend adding a new instance of `CopyWebpackPlugin` directly. Ours is accessible within `config.plugins`, but not by name. It's always last, but that's certainly not reliable.

```js
console.log(config.plugins);
/*
[
  //...
  LoaderOptionsPlugin { options: { minimize: true, test: [Object] } },
  ModuleConcatenationPlugin { options: {} },
  ReplaceText {
    options: { include: /babel-helper$/, exclude: false, patterns: [Array] },
    values: { include: /babel-helper$/, exclude: false, patterns: [Array] },
    patterns:
     Map {
       /throw\s+(new\s+)?(Type|Reference)?Error\s*\(/g => [Function: value] },
    isMatch: [Function] },
  { apply: [Function: apply] } // <~~ CopyWebpackPlugin
]
*/
```

Hope that helps; sorry for the delay!

**Comment by psabharwal123** [comment]
thanks, i ll try to submit a PR in copy webpack to return a class, since i need to remove the copywebpack plugin added by preact-cli.

**Comment by Tam** [comment]
Since `CopyWebpackPlugin` happens to be the only plugin that I'm using that returns an object instead of a class I'm accessing it by calling it `"Object"` (the plain objects constructor name):

```js
helpers.getPluginsByName(config, "Object")[0]
```

Obviously this falls apart when you have more that one plugin that returns an object, but as a temporary fix it does the job.
