### ISSUE TITLE
if url is opened directly in the browser then the page source showing the content of home page

### ISSUE THREAD

**Issue by anuragnagarkota** [developit/preact-cli#598]
Hi 
I have just created an app and build it using preact cli. But strange thing is when I open the /profile route directly in the browser then its page source is showing the content of home route. Will it not affect the seo because the crawlers will get the content of home route on every page of the website.???

Please look into this matter. Thanks

**Do you want to request a *feature* or report a *bug*?**

**What is the current behaviour?**

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version
- npm version
- Operating system
- CLI version
- Browser

**Comment by developit** [comment]
Hi @anuragnagarkota! Search crawlers run JavaScript, so doesn't affect SEO.

Because Preact CLI is generates static files, we can't render arbitrary content for any URL without knowing that information at build time.

If you'd like to serve up route-specific prerendered HTML, you can [use `prerender-urls.json` to define a list of URLs to prerender content for](https://github.com/developit/preact-cli#prerender-multiple-routes):

**prerender-urls.json**: _(in your project root folder)_

```js
[
  {
    "url": "/",
    "title": "Homepage"
  },
  {
    "url": "/profile",
    "title": "User Profile"
  }
]
```
