### ISSUE TITLE
How to debug bugs that only appear in production bundle?

### ISSUE THREAD

**Issue by photz** [developit/preact-cli#609]
**Do you want to request a *feature* or report a *bug*?**

Strictly speaking this is neither a bug report nor a feature request, but mainly a question.  The problem I'm facing is that my app runs fine when I do `npm run dev` but bugs appear when I do `npm run build`.  Specifically the Slider component of preact-material-components does not work properly in the production bundle.  
What are some steps I can undertake to figure out what exactly causes the bugs in the production build?

**What is the current behaviour?**

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version
- npm version
- Operating system
- CLI version
- Browser

**Comment by developit** [comment]
@photz I believe there is a `--no-compress` flag you could pass to `preact build` (or `npm run build -- --no-compress`) that would help here.

FWIW there's [very little going on in preact-material-components Slider](https://github.com/prateekbh/preact-material-components/blob/master/Slider/Slider.jsx) that could reasonably change between development and production, so I am wondering if the issue is actually in the upstream mdc/slider?

**Comment by prateekbh** [comment]
@photz can u explain a bit more

**Comment by photz** [comment]
I found out that what happened was this:
https://github.com/material-components/material-components-web/tree/master/packages/mdc-slider#preventing-fouc

Apart from this particular issue I was also generally wanted to know how I can better debug issues that arise from differences between dev and production builds.
