### ISSUE TITLE
"Uncaught ReferenceError: process is not defined" when importing web3

### ISSUE THREAD

**Issue by borovik96** [developit/preact-cli#766]
**Do you want to request a _feature_ or report a _bug_?**
Bug report

**What is the current behaviour?**
"Uncaught ReferenceError: process is not defined" when importing web3

**If the current behaviour is a bug, please provide the steps to reproduce.**
https://github.com/borovik96/preact-cli-bug/tree/master

![image](https://user-images.githubusercontent.com/9018702/54829628-dd820780-4cc7-11e9-90c5-ff1962e5078f.png)

**What is the expected behaviour?**
No error

**Please mention other relevant information.**

- Node version v8.15.0 (also with v11.10.0)
- npm version 6.4.1 (also with 6.7.0)
- Operating system macOS Mojave 10.14.3
- CLI version 2.2.1
- Browser chrome 72.0.3626.121

**Comment by borovik96** [comment]
I found https://github.com/developit/preact-cli/issues/596 issue, but `web3` library is supposed to work in a browser and it does (with custom webpack config or CRA)

**Comment by ForsakenHarmony** [comment]
can you try `preact-cli@next`?

**Comment by borovik96** [comment]
Yes, same error: 
![image](https://user-images.githubusercontent.com/9018702/54849330-f81ea580-4cf4-11e9-97ec-69cf3d1e5a6b.png)

**Comment by ForsakenHarmony** [comment]
Can you post the line from `web3`?

**Comment by borovik96** [comment]
Sorry, which line exactly? Error thrown not from web3, but from `readable-browser`, which is webpack dependency as I know

**Comment by ForsakenHarmony** [comment]
Put this in `preact.config.js`

```js
export default (config) => {
	delete config.node;
};
```

the shims are excluded by default because they can be quite big

**Comment by borovik96** [comment]
That works, thank you a lot! But can't it have a bad impact for other code?

**Comment by ForsakenHarmony** [comment]
Nah don't remember anyone having a problem, libraries that want to support browsers shouldn't rely on polyfills

**Comment by lukeed** [comment]
They won't "cause problems" necessarily, but it _will_ definitely increase your bundle size, while also making it very (easily) possible to include server-side modules in your client code.

It's generally best to leave the node shims disabled, by default, so as to prevent this from happening... but as you've found, some libraries don't separate them completely.

You may also try using the `'mock'` shims, instead of allowing the whole shim outright. Often times, libraries like this are just doing something simple (eg, `process.env.NODE_ENV === ???`) and don't require the full `process` (or others') functionalities. 

So, something like this – turning on each "mock" shim one at a time, to see what your libraries' are relying on:

```js
module.exports = function (config) {
  config.node.process = 'mock';
}
```

If that still causes issues, you'd change `'mock'` to `true`, which provides the complete shim.

> https://webpack.js.org/configuration/node#node

**Comment by borovik96** [comment]
Thanks a lot, that configuration works for me:

```javascript
  config.node.process = 'mock';
  config.node.Buffer = true; 
```

**Comment by Nagibaba** [comment]
I found the best solution.

The problem is because you lose `window.process` variable, and process exists only on node, not the browser.

So you should inject it to browser when the app loads.

Add this line to your app

```
    window.process = {
      ...window.process,
    };
